- name: kube servers deployment
  hosts: 192.168.1.32
  become: true
  remote_user: kmaster
  tasks:
    - name: create resources
      command: kubectl create configmap demo-config --from-file=/home/kmaster/k8_msydevops_php/pv_mysql.yaml
      become_user: kmaster

    - name: create Kubernetes pv resources
      command: kubectl apply -f /home/kmaster/k8_msydevops_php/pv_mysql.yaml
      become_user: kmaster

    - name: create Kubernetes secrets resources
      command: kubectl apply -f /home/kmaster/k8_msydevops_php/secrets_mysql.yaml
      become_user: kmaster
      
    - name: create Kubernetes mysql pod resources
      command: kubectl apply -f /home/kmaster/k8_msydevops_php/mysql_pod.yaml
      become_user: kmaster
      
    - name: create Kubernetes phpmyadmin pod resources
      command: kubectl apply -f /home/kmaster/k8_msydevops_php/phpmyadmin.yaml
      become_user: kmaster
      
    - name: create Kubernetes apache pod resources
      command: kubectl apply -f /home/kmaster/k8_msydevops_php/apache.yaml
      become_user: kmaster
      